version: '3.7'

services:
  telegraf:
    image: telegraf
    container_name: telegraf
    restart: always
    volumes:
    - "./telegraf.conf:/etc/telegraf/telegraf.conf:ro"
    depends_on:
      - influxdb
    links:
      - influxdb
    ports:
    - '8125:8125'
    environment:
    - INFLUX_TOKEN=$INFLUX_TOKEN
    - INFLUX_ORG=$INFLUX_ORG
    - INFLUX_BUCKET_PRIMARY=$INFLUX_BUCKET_PRIMARY
    - MQTT_USER=$MQTT_USER
    - MQTT_PASS=$MQTT_PASS
    - MQTT_SERVER=$MQTT_SERVER

  influxdb:
    image: influxdb:latest
    container_name: influxdb
    restart: always
    environment:
      - INFLUXDB_DB=influx
      - INFLUXDB_ADMIN_USER=$INFLUXDB_ADMIN_USER
      - INFLUXDB_ADMIN_PASSWORD=$INFLUXDB_ADMIN_PASSWORD
    ports:
      - '8086:8086'
    volumes:
      - "./influxdb:/var/lib/influxdb"

  grafana:
    image: grafana/grafana
    container_name: grafana-server
    restart: always
    depends_on:
      - influxdb
    environment:
      - GF_SECURITY_ADMIN_USER=$GF_SECURITY_ADMIN_USER
      - GF_SECURITY_ADMIN_PASSWORD=$GF_SECURITY_ADMIN_PASSWORD
      - GF_INSTALL_PLUGINS=
    links:
      - influxdb
    ports:
      - '3000:3000'
    volumes:
      - "./graphana:/var/lib/grafana"

  mosquitto:
    image: "eclipse-mosquitto"
    container_name: mosquitto
    ports:
      - 1883:1883
      - 8883:8883
      - 9001:9001
    volumes:
        - "./mosquitto/config:/mosquitto/config"
        - "./mosquitto/data:/mosquitto/data"
        - "./mosquitto/log:/mosquitto/log"
  