substitutions:
  device_name: "xiaomi-miscale-ble-1"
  friendly_name: "Xiaomi Miscale"
  mqqt_root_topic: "device"
  mqqt_retain_message: "false"

ota:
  safe_mode: true
  password: !secret ota_password

esphome:
  name: ${device_name}

esp32:
  board: nodemcu-32s

# Enable logging
logger:
  level: DEBUG
  baud_rate: 9600

wifi:
  networks:
  - ssid: !secret wifi_ssid_home
    password: !secret wifi_password_home
  - ssid: !secret wifi_ssid_makerspace
    password: !secret wifi_password_makerspace


captive_portal:

mqtt:
  broker: "192.168.0.200"
  discovery_object_id_generator: device_name
  topic_prefix: ${mqqt_root_topic}/${device_name}


esp32_ble_tracker:

# logger:
#   level: VERY_VERBOSE


sensor:
  - platform: xiaomi_miscale
    id: scales 
    mac_address: 'EC:DF:ED:DE:7F:6F'
    weight:
      name: "weight"
      force_update: True
      state_topic: ${mqqt_root_topic}/${device_name}/scales/weight/get
    impedance:
      name: "impedance"
      force_update: True
      state_topic: ${mqqt_root_topic}/${device_name}/scales/impedance/get



