
esp8266:
  board: d1_mini

esphome:
  name: blink_test

ota:

logger:
  level: DEBUG
  baud_rate: 9600

wifi:
  networks:
  # - ssid: !secret wifi_ssid_home
  #   password: !secret wifi_password_home
  - ssid: !secret wifi_ssid_makerspace
    password: !secret wifi_password_makerspace


captive_portal:

mqtt:
  broker: "192.168.20.205"

output:
  - platform: slow_pwm
    pin: GPIO2
    id: my_slow_pwm
    period: 500ms