substitutions:
  device_name: "pzem-016-1"
  friendly_name: "PZEM-016 power meter 1"
  mqqt_root_topic: "device"
  mqqt_retain_message: "false"

ota:
  safe_mode: true
  password: !secret ota_password

esphome:
  name: ${device_name}

esp8266:
  board: esp12e

# Enable logging
logger:
  level: DEBUG
  baud_rate: 9600

wifi:
  networks:
  - ssid: !secret wifi_ssid_home
    password: !secret wifi_password_home
  - ssid: !secret wifi_ssid_makerspace
    password: !secret wifi_password_makerspace


captive_portal:

mqtt:
  broker: "192.168.0.200"
  discovery_object_id_generator: device_name
  topic_prefix: ${mqqt_root_topic}/${device_name}

# logger:
#   level: VERY_VERBOSE


globals:
  - id: last_energy
    type: uint32_t
    restore_value: no
    initial_value: '0'
  
uart:
  rx_pin: GPIO3
  tx_pin: GPIO1
  baud_rate: 9600

modbus:

sensor:
  - platform: pzemac
    current:
      name: "current"
      force_update: True
      state_topic: ${mqqt_root_topic}/${device_name}/pzem_016/current/get
    voltage:
      name: "voltage"
      force_update: True
      state_topic: ${mqqt_root_topic}/${device_name}/pzem_016/voltage/get
    energy:
      name: "energy"
      internal: True
      force_update: True
      on_value:
        - lambda: !lambda |-
            id(last_energy) = x;
    power:
      name: "power"
      force_update: True
      state_topic: ${mqqt_root_topic}/${device_name}/pzem_016/power/get
    frequency:
      name: "frequency"
      force_update: True
      state_topic: ${mqqt_root_topic}/${device_name}/pzem_016/frequency/get
    power_factor:
      name: "power_factor"
      force_update: True
      state_topic: ${mqqt_root_topic}/${device_name}/pzem_016/power_factor/get
    update_interval: 5s
  - platform: template
    name: "energy"
    id: energy_template
    update_interval: 60s
    force_update: True
    lambda: !lambda |-
      if (id(last_energy) > 0) { 
        return (id(last_energy));
      } else {
        return {};
      }  
    state_topic: ${mqqt_root_topic}/${device_name}/pzem_016/energy/get


