substitutions:
  scales_window_size: "10"
  scales_send_every: "10"
  scales_send_first_at: "10"
  scales_sample_rate: "500ms"
  scales_gain: "32"
  device_name: "indoor_temperature"
  friendly_name: "Indoor temperature sensor"
  mqqt_root_topic: "device"
  mqqt_retain_message: "false"

ota:
  safe_mode: true
  password: !secret ota_password

esphome:
  name: ${device_name}

  esp8266:
    board: esp12e

# Enable logging
logger:
  level: DEBUG
  baud_rate: 9600

# # Enable Home Assistant API
# api:
#   password: ""

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  ap:
    ssid: "Fallback Hotspot"
    password: !secret wifi_ap_password


captive_portal:

mqtt:
  broker: "192.168.0.200"
  discovery_object_id_generator: device_name
  discovery_unique_id_generator: mac
  topic_prefix: ${mqqt_root_topic}/${device_name}


dallas:
  - pin: GPIO5
    update_interval: 5s

sensor:
  - platform: adc
    pin: A0
    name: "battery"
    update_interval: 10s
    unit_of_measurement: V
    raw: true
    state_topic: ${mqqt_root_topic}/${device_name}/adc/battery/get
    retain: ${mqqt_retain_message}
    filters:
    - multiply: 0.00458030112923
  
  - platform: dallas
    index: 0
    name: "temperature"
    unit_of_measurement: "°C"
    state_topic: ${mqqt_root_topic}/${device_name}/ds18b20/temp/get
    retain: ${mqqt_retain_message}
    on_value:
      then:
        - switch.turn_on: onboard_led
        - delay: 2s
        - switch.turn_off: onboard_led
  
switch:
  - platform: gpio
    id: onboard_led
    pin: GPIO2
    name: "Onboard led"
    state_topic: ${mqqt_root_topic}/${device_name}/gpio/led/get
    retain: ${mqqt_retain_message}




